CATEGORIES = [
    {"name": "Restaurants", "count": "82 places", "icon": "Dining"},
    {"name": "Hospitals", "count": "34 providers", "icon": "Health"},
    {"name": "Home Cleaning", "count": "28 teams", "icon": "Home"},
    {"name": "Packers and Movers", "count": "17 movers", "icon": "Move"},
    {"name": "Dentists", "count": "41 clinics", "icon": "Smile"},
    {"name": "Hotels", "count": "26 stays", "icon": "Stay"},
    {"name": "Electricians", "count": "19 experts", "icon": "Power"},
    {"name": "Beauty Parlours", "count": "37 salons", "icon": "Beauty"},
    {"name": "Event Planners", "count": "14 planners", "icon": "Events"},
    {"name": "Car Rentals", "count": "23 vendors", "icon": "Travel"},
    {"name": "Gyms", "count": "29 studios", "icon": "Fitness"},
    {"name": "Pet Clinics", "count": "11 centers", "icon": "Pets"},
]

BUSINESSES = [
    {
        "id": 1,
        "name": "Saffron Courtyard",
        "category": "Restaurants",
        "area": "Indiranagar",
        "rating": 4.8,
        "reviews": 1284,
        "verified": True,
        "premium": True,
        "openNow": True,
        "offer": "15% off on family dining",
        "priceBand": "$$",
        "summary": "Modern Indian dining with rooftop seating, fast table booking, and curated lunch combos.",
        "services": ["Table Booking", "Delivery", "Party Orders", "Family Dining"],
        "hours": "11:30 AM - 11:00 PM",
        "phone": "+91 98765 20001",
        "leadMessage": "Looking for table booking and weekend offers.",
        "reviewQuote": "Fast seating, polished service, and great for customer meetings.",
    },
    {
        "id": 2,
        "name": "Medisphere Multi-Speciality",
        "category": "Hospitals",
        "area": "Koramangala",
        "rating": 4.6,
        "reviews": 942,
        "verified": True,
        "premium": False,
        "openNow": True,
        "offer": "24x7 emergency support",
        "priceBand": "$$$",
        "summary": "A trusted hospital listing with specialist discovery, OPD booking guidance, and emergency contact visibility.",
        "services": ["Cardiology", "Orthopedics", "Diagnostic Lab", "Ambulance"],
        "hours": "Open 24 hours",
        "phone": "+91 98765 20002",
        "leadMessage": "Need consultation and diagnostics information.",
        "reviewQuote": "Patients mention quick admission coordination and accessible specialists.",
    },
    {
        "id": 3,
        "name": "Spark Home Care",
        "category": "Home Cleaning",
        "area": "HSR Layout",
        "rating": 4.7,
        "reviews": 611,
        "verified": True,
        "premium": False,
        "openNow": True,
        "offer": "Free sofa shampoo with deep cleaning",
        "priceBand": "$$",
        "summary": "Residential and office cleaning teams with deep clean packages, same-day slots, and WhatsApp confirmation.",
        "services": ["Deep Cleaning", "Kitchen Cleaning", "Office Cleaning", "Sofa Shampoo"],
        "hours": "8:00 AM - 8:00 PM",
        "phone": "+91 98765 20003",
        "leadMessage": "Need a home deep cleaning quote.",
        "reviewQuote": "Reliable service windows and clear package pricing stand out.",
    },
    {
        "id": 4,
        "name": "SwiftLift Relocations",
        "category": "Packers and Movers",
        "area": "Whitefield",
        "rating": 4.5,
        "reviews": 407,
        "verified": True,
        "premium": True,
        "openNow": False,
        "offer": "Free packing material on 2BHK move",
        "priceBand": "$$",
        "summary": "Local and intercity movers with survey booking, packaging add-ons, and insurance visibility.",
        "services": ["Home Relocation", "Office Shift", "Vehicle Transport", "Packing Support"],
        "hours": "9:00 AM - 7:00 PM",
        "phone": "+91 98765 20004",
        "leadMessage": "Need shifting estimate for a 2BHK apartment.",
        "reviewQuote": "Customers like the survey-first approach and itemized estimates.",
    },
    {
        "id": 5,
        "name": "Pearl Dental Studio",
        "category": "Dentists",
        "area": "Jayanagar",
        "rating": 4.9,
        "reviews": 519,
        "verified": True,
        "premium": False,
        "openNow": True,
        "offer": "",
        "priceBand": "$$",
        "summary": "Family dental clinic showcasing appointment support, treatment specialties, and review-backed trust.",
        "services": ["Root Canal", "Aligners", "Cosmetic Dentistry", "Kids Dentistry"],
        "hours": "10:00 AM - 8:30 PM",
        "phone": "+91 98765 20005",
        "leadMessage": "Need dental consultation for weekend slot.",
        "reviewQuote": "Known for smooth appointment handling and transparent treatment plans.",
    },
    {
        "id": 6,
        "name": "Amber Nest Business Hotel",
        "category": "Hotels",
        "area": "Indiranagar",
        "rating": 4.4,
        "reviews": 756,
        "verified": True,
        "premium": True,
        "openNow": True,
        "offer": "Corporate rate with breakfast included",
        "priceBand": "$$$",
        "summary": "A hotel listing demo with room categories, amenity highlights, and direct reservation callbacks.",
        "services": ["Executive Rooms", "Airport Pickup", "Meeting Hall", "Free Breakfast"],
        "hours": "Open 24 hours",
        "phone": "+91 98765 20006",
        "leadMessage": "Need room availability and corporate pricing.",
        "reviewQuote": "Frequent travelers mention dependable check-in and meeting-friendly spaces.",
    },
    {
        "id": 7,
        "name": "WireWise Electricals",
        "category": "Electricians",
        "area": "BTM Layout",
        "rating": 4.6,
        "reviews": 332,
        "verified": True,
        "premium": False,
        "openNow": True,
        "offer": "30-minute callback promise",
        "priceBand": "$",
        "summary": "On-demand electricians for residential fixes, installations, and emergency troubleshooting.",
        "services": ["Wiring Repair", "Fan Installation", "MCB Fix", "Emergency Visits"],
        "hours": "7:30 AM - 10:00 PM",
        "phone": "+91 98765 20007",
        "leadMessage": "Need electrician for urgent repair.",
        "reviewQuote": "Quick response and clear service notes make this easy to trust in a demo.",
    },
    {
        "id": 8,
        "name": "Velvet Leaf Salon",
        "category": "Beauty Parlours",
        "area": "Koramangala",
        "rating": 4.7,
        "reviews": 884,
        "verified": True,
        "premium": True,
        "openNow": False,
        "offer": "Flat 20% off on bridal consultation",
        "priceBand": "$$",
        "summary": "Salon showcase card with service menus, consultation bookings, and festive package promotions.",
        "services": ["Hair Spa", "Bridal Makeup", "Facials", "Nail Studio"],
        "hours": "10:00 AM - 9:00 PM",
        "phone": "+91 98765 20008",
        "leadMessage": "Need bridal package consultation.",
        "reviewQuote": "Popular for polished presentation and special package discovery.",
    },
    {
        "id": 9,
        "name": "Mint Mile Fitness Hub",
        "category": "Gyms",
        "area": "HSR Layout",
        "rating": 4.5,
        "reviews": 463,
        "verified": False,
        "premium": False,
        "openNow": True,
        "offer": "Free trial session",
        "priceBand": "$$",
        "summary": "Fitness center listing with membership offers, trainer highlights, and visit scheduling.",
        "services": ["Strength Training", "Zumba", "Personal Training", "Nutrition Advice"],
        "hours": "5:30 AM - 10:00 PM",
        "phone": "+91 98765 20009",
        "leadMessage": "Need membership details and trial booking.",
        "reviewQuote": "Strong trial conversion flow for demonstration purposes.",
    },
    {
        "id": 10,
        "name": "PawCure Pet Clinic",
        "category": "Pet Clinics",
        "area": "Whitefield",
        "rating": 4.8,
        "reviews": 216,
        "verified": True,
        "premium": False,
        "openNow": True,
        "offer": "",
        "priceBand": "$$",
        "summary": "Pet care listing with vaccination support, grooming references, and emergency consultation contact.",
        "services": ["Vaccination", "General Checkup", "Surgery", "Pet Pharmacy"],
        "hours": "9:00 AM - 9:00 PM",
        "phone": "+91 98765 20010",
        "leadMessage": "Need pet clinic appointment.",
        "reviewQuote": "Great example for niche category discovery in the same interface.",
    },
    {
        "id": 11,
        "name": "EverAfter Event House",
        "category": "Event Planners",
        "area": "Indiranagar",
        "rating": 4.6,
        "reviews": 287,
        "verified": True,
        "premium": True,
        "openNow": False,
        "offer": "Free decor consultation",
        "priceBand": "$$$",
        "summary": "Event planning vendor discovery with portfolio-style services and lead capture for callbacks.",
        "services": ["Corporate Events", "Weddings", "Decor", "Artist Management"],
        "hours": "10:00 AM - 7:00 PM",
        "phone": "+91 98765 20011",
        "leadMessage": "Need planner for a corporate event.",
        "reviewQuote": "Useful for showing higher-value service enquiries and premium placements.",
    },
    {
        "id": 12,
        "name": "RoadReady Car Rentals",
        "category": "Car Rentals",
        "area": "Jayanagar",
        "rating": 4.4,
        "reviews": 344,
        "verified": True,
        "premium": False,
        "openNow": True,
        "offer": "Weekend chauffeur package",
        "priceBand": "$$",
        "summary": "Rental listing with trip types, car options, and direct booking calls for quick lead conversion.",
        "services": ["Self Drive", "Chauffeur Service", "Airport Transfer", "Outstation Trips"],
        "hours": "6:00 AM - 11:00 PM",
        "phone": "+91 98765 20012",
        "leadMessage": "Need vehicle for airport transfer.",
        "reviewQuote": "A good transportation category to round out the local services mix.",
    },
]
